feat: Switch to GCC 12.
deepin-community/gcc-mingw-w64 pull request #2
Opened 2024-07-05 09:00 UTC by liujianqiang-niu

Switch to GCC 12 for v25

2024-07-05 09:14 UTC, UTsweetyfish requested changes

2024-07-05 09:14 UTC, UTsweetyfish commented on debian/changelog
> +gcc-mingw-w64 (26.1-deepin1) unstable; urgency=medium
```suggestion
gcc-mingw-w64 (26.1deepin1) unstable; urgency=medium
```

2024-07-05 09:14 UTC, UTsweetyfish commented on debian/source/format
> +3.0 (quilt)
```suggestion
3.0 (native)
```

2024-09-10 03:21 UTC, hudeng-go approved these changes

2024-09-10 03:25 UTC, hudeng-go commented
/approve

2024-09-10 05:45 UTC, hudeng-go commented
/unhold

2024-09-10 05:46 UTC, merged